Collaborator list module pr
ohioit/ansible-collection-github pull request #17
Opened 2021-11-19 20:47 UTC by jacobeicher

Module #2

2021-11-29 17:07 UTC, klfgit requested changes

2021-11-29 17:07 UTC, klfgit commented on .github/workflows/linter.yaml
> +        find . -type f -name "*.py" | xargs pylint --exit-zero --disable=C0111
Add a newline.

2021-11-29 17:07 UTC, klfgit commented on docs/collaborator_information.rst
> +There are no further requirements needed to run this module.
This module requires github python api, right?

2021-11-29 17:07 UTC, klfgit commented on playbooks/RepoInformation.yaml
> +---
Delete this file.

2021-11-29 17:07 UTC, klfgit commented on plugins/modules/collaborator_information.py
> +            - GitHub API token used to retrieve information about collaborators in repositories a user has access to
Do not end a sentence with 'to'.  Fix this in all documentation.

For example `GitHub API token used to retrieve information about collaborators in repositories a user has access to` should be something like this
`GitHub API token that can be used to retrieve information about collaborators of repositories to which a user has access.`

2021-11-29 17:07 UTC, klfgit commented on plugins/modules/collaborator_information.py
> +            - The organization that the information is within the scope of.
Do not end sentences with 'of'.  Fix this in all documentation.
e.g. `The organization that the information is within the scope of.` -. `The organization within which to search`

2021-11-29 17:07 UTC, klfgit commented on plugins/modules/collaborator_information.py
> +                colab_list.append(collaborator.login)
Is this needed?

2021-11-29 17:07 UTC, klfgit commented on plugins/modules/collaborator_information.py
> +        for p in to_add:
p is a bad variable name.

2021-11-29 17:07 UTC, klfgit commented on plugins/modules/collaborator_information.py
> +def check_permissions(g, repos, user, permission_level, org_name):
It would be nice for this to return the repo(s) in which the permission did not match.

2021-11-29 17:07 UTC, klfgit commented on plugins/modules/collaborator_information.py
> +            if(collaborator.login in to_remove):
Make the format of the code consistent.

I'm seeing 'if(....)' and 'if (...)'.

2021-11-29 17:07 UTC, klfgit commented on plugins/modules/collaborator_information.py
> +                print("removing " + str(collaborator) + " from " + repo)
delete

2021-11-29 17:07 UTC, klfgit commented on plugins/modules/collaborator_information.py
> +                print("changing " + user + " in " + repo + " from Permission " + r.get_collaborator_permission(user) + " to "  + permssion_level)
delete

2021-11-29 17:07 UTC, klfgit commented on plugins/modules/collaborator_information.py
> +            # collab_output['received_events_url'] = collaborator.received_events_url
Why have these been commented out?  If the code is not needed please delete it.

2021-11-29 17:07 UTC, klfgit commented on plugins/modules/collaborator_information.py
> +            dict_repo.append(collab_output.copy())
Why was it necessary to make a copy?

2021-11-29 17:07 UTC, klfgit commented on plugins/modules/collaborator_information.py
> +        output[repo] = dict_repo.copy()
Why was it necessary to make a copy?

2021-11-29 17:07 UTC, klfgit commented on plugins/modules/collaborator_information.py
> +    valid_permissions = ["push", "pull", "admin"]
The documentation list 'triage'.  Should it be added to this list?

2021-11-29 17:07 UTC, klfgit commented on plugins/modules/collaborator_information.py
> +                module.exit_json(changed=False, failed=True, msg="Invalid permission: " + module.params['collaborators_to_add'][permission] + ". Permissions must be 'push' 'pull' or 'admin'")
Should triage be part of this list?

2021-11-29 17:07 UTC, klfgit commented on plugins/modules/collaborator_information.py
> +    #         del_collaborators(g, target_repos, collaborators_to_remove, org_name)
delete dead code.

2021-11-29 17:07 UTC, klfgit commented on tests/integration/integration_test.yml
> +          result is changed
add missing newline.

2021-11-29 17:07 UTC, klfgit commented on tests/unit/modules/test_github_repo_return.py
> +
add missing new line.

2021-11-29 17:07 UTC, klfgit commented on plugins/modules/collaborator_information.py
> +            add_collaborators(g, module.params['repos'], module.params['collaborators_to_add'])
Does this code work?  add_collaborators is defined as taking 4 argument.  Here it is being called with 3 arguments.

2022-01-25 23:25 UTC, closed without merging

2022-10-08 01:03 UTC, dannysauer commented on plugins/modules/collaborator_information.py
> +            - GitHub API token used to retrieve information about collaborators in repositories a user has access to
English is not Latin. :shrug: 

https://www.merriam-webster.com/words-at-play/prepositions-ending-a-sentence-with