Module 1 & 2
ohioit/ansible-collection-github pull request #18
Opened 2022-01-27 21:45 UTC by jacobeicher

2022-01-31 16:31 UTC, robert4man commented on .github/workflows/ansible-test.yml
> +          TOKEN: ${{ secrets.GITHUB_TOKEN }}
We cannot accept this PR with this integration workflow present/active.

2022-02-01 20:27 UTC, klfgit requested changes

2022-02-01 20:27 UTC, klfgit commented on tests/utils/render.sh
> +main "$@"
add newline.

2022-02-01 20:27 UTC, klfgit commented on plugins/modules/repository_information.py
> +                about repositories to which a user has access to
to which a user has access to -> to which a user has access

2022-02-01 20:27 UTC, klfgit commented on plugins/modules/repository_information.py
> +    if module.check_mode:
add a blank line above this line.

2022-02-01 20:27 UTC, klfgit commented on plugins/modules/collaborator_information.py
> +            - GitHub API token used to retrieve information about collaborators in repositories a user has access to
repositories a user has access to -> repositories to which a user has access.

2022-02-01 20:27 UTC, klfgit commented on plugins/modules/collaborator_information.py
> +        output[repo] = dict_repo.copy()
The calls to copy seem unnecessary.

2022-02-01 20:27 UTC, klfgit commented on plugins/modules/collaborator_information.py
> +        dict_repo = list()
The name of the var is dict_repo but it is initialized with a list.  Please change the var name to something more meaning full.

2022-02-01 20:27 UTC, klfgit commented on plugins/modules/collaborator_information.py
> +    if(module.params['collaborators_to_add']):
Always have a space after the 'if'.

2022-02-01 20:27 UTC, klfgit commented on plugins/modules/collaborator_information.py
> +        for permission in module.params['collaborators_to_add']:
Each time through the loop permission actually holds a user name and not a permission value.  Given this 'permission' seem like a bad name for the loop variable.

2022-02-01 20:27 UTC, klfgit commented on plugins/modules/collaborator_information.py
> +            collaborator_list.append(collaborator.login)
Use a set instead of a list.  Using a list results in line 247 having to do a linear search each time it is called.

2022-02-01 20:27 UTC, klfgit commented on plugins/modules/collaborator_information.py
> +        for user in user_to_check.items():
To make this more readable do 
```
for user, permission in user_to_check.items() :  
    if r.get_colaborator_permission(user) != permission : 
        ....
```

2022-02-01 20:27 UTC, klfgit commented on plugins/modules/collaborator_information.py
> +def check_permissions(g, repos, user_to_check):
This does not return which user  or the repo in which the differences was found.  How are playbook authors intended to use check_permissions?

2022-02-01 20:27 UTC, klfgit commented on plugins/modules/collaborator_information.py
> +            r.add_to_collaborators(p, permission=to_add[p])
What happens if the user is already a collaborator?

2022-02-01 20:27 UTC, klfgit commented on plugins/modules/collaborator_information.py
> +            collaborator_list.append(collaborator.login)
None of this is being used.  Was the goal to use collaborator_list to control how which users are added?

2022-02-14 13:19 UTC, klfgit requested changes

2022-02-14 13:19 UTC, klfgit commented on .github/workflows/linter.yaml
> +
Use a consistent version of python in the GitHub workflows.  The ansible test  workflow is using 3.6.9.  Please use 3.9.x for all workflows.

2022-02-14 13:19 UTC, klfgit commented on plugins/modules/collaborator_information.py
> +        if p in collaborator_set:
p is a bad variable name.  Please change it to something more meaningful.

2022-02-14 13:19 UTC, klfgit commented on plugins/modules/collaborator_information.py
> +
This code does not work.  Please fix the bug and add unit tests that would have found the bug.

2022-02-14 13:21 UTC, klfgit commented on plugins/modules/collaborator_information.py
> +
output will be populated with objects that have the same values for all fields.

2022-03-08 16:23 UTC, closed without merging